MODULE YOMWAKE

USE PARKIND1  ,ONLY : JPRB

IMPLICIT NONE

SAVE

REAL(KIND=JPRB) :: WAPECUT
REAL(KIND=JPRB) :: SIGMAD
REAL(KIND=JPRB) :: HWMIN
REAL(KIND=JPRB) :: SIGMAW_MAX
REAL(KIND=JPRB) :: DENS_RATE
REAL(KIND=JPRB) :: WDENSMIN
REAL(KIND=JPRB) :: STARK
REAL(KIND=JPRB) :: ALPK
REAL(KIND=JPRB) :: WDENS_REF(2)
REAL(KIND=JPRB) :: COEFGW
REAL(KIND=JPRB) :: TAU_CV
REAL(KIND=JPRB) :: CREP_UPPER
REAL(KIND=JPRB) :: CREP_SOL
REAL(KIND=JPRB) :: DELTA_T_MIN
REAL(KIND=JPRB) :: RZERO

!    ------------------------------------------------------------------
END MODULE YOMWAKE     
